streams:
  replicas: 2
  
  # Your Streams App Image.
  image:
    registry: docker.wai
    repository: "yunan/kstreams-mavenapp"
    tag: 0.0.4

  # e.g.)
  # nodeSelector:
  #   alpaka/node-type: worker
  nodeSelector: {}
    
  kafka: 
    # Your Kafka Broker API
    server: "testbed-kafka-headless:9092"
    # If true, Streams waits Kafka
    readinessCheck:
      enabled: true

env:
  - name: KEY
    value: sample-env
  # - name: KEY
  #   value: ${MY_SECRET_KEY}