apiVersion: skaffold/v4beta3 
kind: Config 

build:
  local:
    push: false                  # 로컬(도커 데몬)에서만 빌드 # push하고싶을땐 cli에서 --default-repo와 --push옵션 추가
  artifacts: []
  #  - image: xxxxx              # 생성할 이미지 이름(repository) 지정
  #    context: xxx/xxx          # dockerfile 및 관련 파일 위치
  
deploy:
  helm:                          # skaffold로 deploy동작이 포함된 명령어 실행시, helm으로 이를 수행하겠다는 뜻
    releases: []
      # - name: xxx              # 릴리즈 이름
      #   chartPath: xxx         # Helm 차트 경로 (소스코드, 아카이브 둘 다 가능)
      #   skipBuildDependencies: true
      #   valueFiles: xxx.yml    # Helm 실행시 사용될 value 파일
      #   setValueTemplates: xxx # 추가로 설정할 value

# skaffold 실행시 profile을 선택하여 위 build, deploy 등에 Override할 수 있다.
profiles:
  - name: mavenapp
    patches:
      - op: add
        path: /build/artifacts
        value:
          - image: kstreams-mavenapp   
            context: values/images/mavenapp/
      - op: add
        path: /deploy/helm/releases
        value:
          - name: kstreams-mavenapp-sample
            chartPath: kstreams/
            skipBuildDependencies: true
            valueFiles:
              - values/mavenapp.yaml
      

  