apiVersion: skaffold/v4beta3 
kind: Config 

build:
  local:
    push: false                  # 로컬(도커 데몬)에서만 빌드 # push하고싶을땐 cli에서 --default-repo와 --push옵션 추가
  artifacts: []
  #  - image: xxxxx              # 생성할 이미지 이름(repository) 지정
  #    context: xxx/xxx          # dockerfile 및 관련 파일 위치
  
deploy:
  helm:                          # skaffold로 deploy동작이 포함된 명령어 실행시, helm으로 이를 수행하겠다는 뜻
    releases: []
      # - name: xxx              # 릴리즈 이름
      #   chartPath: xxx         # Helm 차트 경로 (소스코드, 아카이브 둘 다 가능)
      #   skipBuildDependencies: true
      #   setValueTemplates: xxx # Helm 배포시 개별 value 할당. valuesFiles보다 우선순위가 높다.
      #   valuesFiles: xxx.yml   # Helm 배포시 overriding values 파일. setValueTemplates 대상 외 나머지 value들만 할당
                                 # 우선순위 skaffold CLI options > setValueTemplates > valuesFiles
      
# skaffold 실행시 profile을 선택하여 위 build, deploy 등에 Override할 수 있다.
profiles:
  - name: mavenapp
    patches:
      - op: add
        path: /build/artifacts
        value:
          - image: kstreams-mavenapp   
            context: sample-values/mavenapp/image/
      - op: add
        path: /deploy/helm/releases
        value:
          - name: kstreams-mavenapp
            chartPath: chartrepo/kstreams-0.0.4.tgz
            skipBuildDependencies: true
            setValueTemplates:
              streams.kafka.readinessCheck.enabled: false
              streams.image.registry: "{{ .IMAGE_DOMAIN_kstreams_mavenapp }}"
              streams.image.repository: "{{ .IMAGE_REPO_NO_DOMAIN_kstreams_mavenapp }}"
              streams.image.tag: "{{ .IMAGE_TAG_kstreams_mavenapp }}"
            valuesFiles: 
              - sample-values/mavenapp/value.yaml

        