streams:
  replicas: 1
  podAnnotations: {}
  affinity: {}
  tolerations: {}
  resources: {}
  
  # e.g.)
  # nodeSelector:
  #   alpaka/node-type: worker
  nodeSelector: {}
  
  # Your Streams App.
  image:
    registry: ""
    repository: "library/streams"
    tag: latest

  env:
    - name: KEY
      value: sampleenv
    # - name: KEY
    #   value: ${MY_SECRET_KEY}
  
  kafka: 
    # Your Kafka Broker API
    server: "testbed-kafka-headless:9092"
    readinessCheck:
      enabled: false
      image: bitnami/kafka:latest
      
